### ISSUE TITLE
at_exit program executors broken in jruby 9.3

### ISSUE THREAD

**Issue by cshupp1** [jruby/jruby#6887]
Consider the following docker-compose.yml file

```
version: "3.9"

services:
  jruby_toy:
    container_name: jr_toy
    image: jruby:latest
    volumes:
      - ./:/jr_toy
    working_dir: /jr_toy
    command: jruby ./toy.rb

volumes:
  shared:
```

toy.rb is as follows:
```

at_exit do
  puts "Goodbye Ruby!!"
end

java_goodbye = java.lang.Thread.new(->() {puts "Goodby from Java!"})

java.lang.Runtime.getRuntime.addShutdownHook(java_goodbye)

puts "jruby is #{JRUBY_VERSION}"

java.lang.Thread.currentThread.join
```

on a docker-compose up we see:
```
D:\work\docker_direct_image\jr_toy>docker-compose up
Creating network "jr_toy_default" with the default driver
Creating jr_toy ... done
Attaching to jr_toy
jr_toy       | jruby is 9.3.0.0
```

on a down:
```
D:\work\docker_direct_image\jr_toy>docker-compose up
Creating network "jr_toy_default" with the default driver
Creating jr_toy ... done
Attaching to jr_toy
jr_toy       | jruby is 9.3.0.0
jr_toy       | Goodby from Java!
jr_toy exited with code 143
```

running in this fashion *does* work (note that the final join on the current thread is removed):
```
D:\work\docker_direct_image\jr_toy>docker run -it -v D:\work\docker_direct_image\jr_toy:/jr_toy jruby:latest bash
root@4d299c7a3524:/# cd /jr_toy/
root@4d299c7a3524:/jr_toy# jruby toy.rb
jruby is 9.3.0.0
Goodbye Ruby!!
Goodby from Java!
```

Suppose I Ieave that join in:
```
root@4d299c7a3524:/jr_toy# jruby toy.rb
jruby is 9.3.0.0
^CGoodby from Java!
```

Killing via ctrl-c causes at_exit to not run.

I discovered that our rails application at_exit blocks do not run as expected.

Host machine is windows.
