### ISSUE TITLE
Inconsistent dependency resolution between JRuby and MRI

### ISSUE THREAD

**Issue by sschuberth** [jruby/jruby#6893]
**Environment Information**

I'm using the ruby-complete Maven artifact in version 9.3.1.0 (I also tried version 9.2.17.0) to programmatically run [this script](https://github.com/oss-review-toolkit/ort/blob/jruby/analyzer/src/main/resources/scripts/bundler_resolve_dependencies.rb)

```
require 'bundler'

definition = Bundler.definition()

definition.resolve_remotely!

definition.specs.each do |spec|
  puts("\0")
  puts(spec.to_yaml)
end
```

on a very simple [test project](https://github.com/oss-review-toolkit/ort/tree/jruby/analyzer/src/funTest/assets/projects/synthetic/bundler/lockfile) whose lock file looks like

```
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.3)
    mini_portile2 (2.4.0)
    nokogiri (1.10.8)
      mini_portile2 (~> 2.4.0)
    nokogiri (1.10.8-x64-mingw32)
      mini_portile2 (~> 2.4.0)
    rack (2.1.4)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.1)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.1)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  nokogiri
  rack (~> 2.1)
  rspec
```

**Expected Behavior**

Running the script with MRI shows the following spec for *nokogiri*

```
--- !ruby/object:Bundler::EndpointSpecification
name: nokogiri
version: !ruby/object:Gem::Version
  version: 1.10.8
platform: ruby
authors: []
autorequire: 
bindir: bin
cert_chain: []
date: 
dependencies:
- !ruby/object:Gem::Dependency
  name: mini_portile2
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: 2.4.0
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: 2.4.0
description: 
email: 
executables: []
extensions: []
extra_rdoc_files: []
files: []
homepage: 
licenses: []
metadata: {}
post_install_message: 
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: 2.3.0
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
requirements: []
rubygems_version: 3.0.6
signing_key: 
specification_version: 4
summary: 
test_files: []
```

and I'd expect running with JRuby to return the same result.

**Actual Behavior**

JRuby instead returns

```
name: nokogiri
version: !ruby/object:Gem::Version
  version: 1.10.8
platform: ruby
authors: []
autorequire:
bindir: bin
cert_chain: []
date:
dependencies: []
description:
email:
executables: []
extensions: []
extra_rdoc_files: []
files: []
homepage:
licenses: []
metadata: {}
post_install_message:
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: 2.3.0
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
requirements: []
rubygems_version: 3.2.29
signing_key:
specification_version: 4
summary:
test_files: []
```

so `dependencies: []` is empty instead of showing `mini_portile2`. As this is the only difference, and for all other gems dependencies are listed fine, I'm clueless what the issue could be one my side. Maybe it's a JRuby issue?

Thanks in advance for any insights.
