### ISSUE TITLE
Regression in JRuby-head with rubocop-ast

### ISSUE THREAD

**Issue by marcandre** [jruby/jruby#7094]
The test-suite for `rubocop-ast` (a core dependency of RuboCop) [fails massively for current JRuby-head](https://github.com/rubocop/rubocop-ast/actions/runs/1834115929).

This gem is very stable; [last run](https://github.com/rubocop/rubocop-ast/runs/4498886255?check_suite_focus=true) was 2 months ago using "jruby-head-ubuntu-20.04.tar.gz"

The failure is sadly deep inside the metaprogramming of the gem. I suspect that [this method](https://github.com/rubocop/rubocop-ast/blob/run/lib/rubocop/ast/node_pattern/compiler/node_pattern_subcompiler.rb#L89) is called and that somehow `node.child` is `nil`?

I have quite an extensive backlog so can't investigate further right now. Maybe a `git bisect` would help pinpoint what could cause the issue?

**Comment by k77ch7** [comment]
This may be related to #7247.  So #7273 could improve this.

**Comment by headius** [comment]
Did it fix the issue?

**Comment by marcandre** [comment]
[Apparently not](https://github.com/rubocop/rubocop-ast/runs/7724638022?check_suite_focus=true).

**Comment by k77ch7** [comment]
umm...

JRuby build version is too old.
```
jruby 9.4.0.0-SNAPSHOT (3.1.0) 2022-04-27 cefd578cef OpenJDK 64-Bit Server VM 11.0.16+8 on 11.0.16+8 [x86_64-linux]
```
https://github.com/rubocop/rubocop-ast/runs/7724638022?check_suite_focus=true#step:4:24

**Comment by k77ch7** [comment]
@eregon 

 Do you have the next release date of [jruby-dev-builder ](https://github.com/ruby/jruby-dev-builder)?

**Comment by eregon** [comment]
It runs daily automatically but fails since April because of https://github.com/jruby/jruby/issues/7106

**Comment by k77ch7** [comment]
That make sense.

**Comment by eregon** [comment]
https://github.com/jruby/jruby/issues/7308 got fixed, so now there is a recent build of jruby-head for setup-ruby.

**Comment by headius** [comment]
Latest runs appear to be green, so I'm optimistically closing this.

**Comment by headius** [comment]
@marcandre Oops, I must have been looking at an old build or a different branch. Will investigate a bit locally.

**Comment by headius** [comment]
One failure on 9.3:

```
  1) RuboCop::AST::RegexpNode#to_regexp with a regexp with an "n" option is expected to eq "/abc/n"
     Failure/Error: it { expect(regexp_node.to_regexp.inspect).to eq('/abc/n') }
     
       expected: "/abc/n"
            got: "/abc/"
     
       (compared using ==)
     # ./spec/rubocop/ast/regexp_node_spec.rb:60:in `block in <main>'
```

Six on master HEAD:

```
  1) RuboCop::AST::RegexpNode#to_regexp with a regexp with an "n" option is expected to eq "/abc/n"
     Failure/Error: it { expect(regexp_node.to_regexp.inspect).to eq('/abc/n') }
     
       expected: "/abc/n"
            got: "/abc/"
     
       (compared using ==)
     # ./spec/rubocop/ast/regexp_node_spec.rb:60:in `block in <main>'

  2) RuboCop::AST::NodePattern predicates with a named argument for which the predicate is true is expected to match code s(:send,
  s(:int, 1), :+,
  s(:int, 2)) and {:param=>1}
     Failure/Error: @cache[:lambda].call(*args, block: block, **rest)
     
     ArgumentError:
       wrong number of arguments (given 3, expected 1)
     # ./lib/rubocop/ast/node_pattern.rb:71:in `match'
     # ./spec/rubocop/ast/node_pattern_spec.rb:33:in `block in matches?'
     # ./spec/rubocop/ast/node_pattern_spec.rb:1224:in `block in <main>'

  3) RuboCop::AST::NodePattern params as named parameters when provided as argument to match is expected to match code s(:int, 10) and {:foo=>#<Object:0x7f5a3e41>}
     Failure/Error: @cache[:lambda].call(*args, block: block, **rest)
     
     ArgumentError:
       wrong number of arguments (given 3, expected 1)
     # ./lib/rubocop/ast/node_pattern.rb:71:in `match'
     # ./spec/rubocop/ast/node_pattern_spec.rb:33:in `block in <main>'
     # ./spec/rubocop/ast/node_pattern_spec.rb:1338:in `block in <main>'

  4) Changelog parses correctly
     Failure/Error: Changelog::Entry.new(type: type, body: "Do something cool#{'x' * i}", user: "johndoe#{'x' * i}")
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./tasks/changelog.rb:24:in `initialize'
     # ./spec/tasks/changelog_spec.rb:46:in `block in entries'
     # ./spec/tasks/changelog_spec.rb:45:in `block in entries'
     # ./spec/tasks/changelog_spec.rb:10:in `block in changelog'
     # ./spec/tasks/changelog_spec.rb:60:in `block in <main>'

  5) Changelog merges correctly
     Failure/Error: Changelog::Entry.new(type: type, body: "Do something cool#{'x' * i}", user: "johndoe#{'x' * i}")
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./tasks/changelog.rb:24:in `initialize'
     # ./spec/tasks/changelog_spec.rb:46:in `block in entries'
     # ./spec/tasks/changelog_spec.rb:45:in `block in entries'
     # ./spec/tasks/changelog_spec.rb:10:in `block in changelog'
     # ./spec/tasks/changelog_spec.rb:64:in `block in <main>'

  6) Changelog Changelog::Entry generates correct content
     Failure/Error: Changelog::Entry.new(type: type, body: "Do something cool#{'x' * i}", user: "johndoe#{'x' * i}")
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./tasks/changelog.rb:24:in `initialize'
     # ./spec/tasks/changelog_spec.rb:46:in `block in entries'
     # ./spec/tasks/changelog_spec.rb:45:in `block in entries'
     # ./spec/tasks/changelog_spec.rb:49:in `block in entry'
     # ./spec/tasks/changelog_spec.rb:53:in `block in <main>'
```
