### ISSUE TITLE
FFI errno spec fails on JRuby on Windows

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#7521]
See https://github.com/ffi/ffi/actions/runs/3673763975/jobs/6211192575
```
 Failures:

  1) FFI.errno FFI.errno contains errno from last function, FFI::LastError.winapi_error works differently per OS
     Failure/Error: expect(FFI::LastError.winapi_error).to eq(0x12345678)

       expected: 305419896
            got: 0

       (compared using ==)
     # ./spec/ffi/errno_spec.rb:28:in `block in <main>'
```

I'll skip it upstream (until fixed) to skip the FFI CI green.
