### ISSUE TITLE
JRuby 9.4.0.0 doesn't parse yaml file

### ISSUE THREAD

**Issue by brometeo** [jruby/jruby#7610]
This yaml code works with JRuby 9.3.8.0, but not with 9.4.0.0:

```
development: &dev
  database: &dev_db
    database: postgresql://localhost/db
    user: user1
    password: pass1

test: &test
  <<: *dev
  database:
    <<: *dev_db
    database: postgresql://localhost/db_test
```

Error given is:

`jruby-9.4.0.0/lib/ruby/stdlib/psych/visitors/to_ruby.rb:432:in 'visit_Psych_Nodes_Alias': Unknown alias: dev (Psych::BadAlias)`
